#! /bin/sh

HERE=`pwd`
PAPI_VER=`ls src | grep papi- | sed -e "s/papi-//"`

rm -rf ./chm
rm -rf ./config.*
rm -rf ./autom4te.cache
rm -rf ./src/Makevars
rm -rf ./src/build_papi
rm -rf ./src/Makedeps
rm -rf ./src/*.dylib
rm -rf ./src/*.so*
rm -rf ./src/*.o
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./src/*.a
rm -rf ./src/*.rc
rm -rf ./src/*.rds
rm -rf ./src-*
rm -rf ./man/*.pdf

rm -rf ./src/build
rm -rf ./inst/libs

rm -rf src/papi-${PAPI_VERSION}/src/ctests/mpifirst

cd ./src/papi-${PAPI_VERSION}/src/ && make clean
cd $HERE
cd ./src/libcipcm && make distclean
cd $HERE

