#! /bin/sh

rm -rf ./chm
rm -rf ./config.*
rm -rf ./autom4te.cache
rm -rf ./src/Makevars
rm -rf ./src/build_papi
rm -rf ./src/Makedeps
rm -rf ./src/*.dylib
rm -rf ./src/*.so*
rm -rf ./src/*.o
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./src/*.a
rm -rf ./src/*.rc
rm -rf ./src/*.rds
rm -rf ./src-*
rm -rf ./man/*.pdf

rm -rf ./src/build
rm -rf ./inst/libs

cd ./src/papi-5.4.1/src/ && make clean
cd `pwd`/src/libcipcm && make distclean
